import argparse
import json
import shutil
import subprocess
import time
from pathlib import Path
from typing import Optional


def _parse_redis_host_port(redis_url: str) -> tuple[str, int]:
    if not redis_url.startswith("redis://"):
        raise ValueError("Redis URL must use redis://host:port format")
    host_port = redis_url[len("redis://") :]
    if "/" in host_port:
        host_port = host_port.split("/", 1)[0]
    if ":" in host_port:
        host, port_str = host_port.rsplit(":", 1)
        return host, int(port_str)
    return host_port, 6379


def _write_setup_env_file(
    *,
    env_file: Path,
    ray_address: str,
    redis_url: str,
    shell_rc: Optional[Path],
) -> None:
    env_file.parent.mkdir(parents=True, exist_ok=True)
    env_file.write_text(
        "# Generated by gpulane setup-stack\n"
        f"export GPULANE_RAY_ADDRESS={json.dumps(ray_address)}\n"
        f"export GPULANE_REDIS_URL={json.dumps(redis_url)}\n",
        encoding="utf-8",
    )
    if shell_rc is None:
        return
    shell_rc.parent.mkdir(parents=True, exist_ok=True)
    shell_rc.touch(exist_ok=True)
    source_line = f'source "{env_file}"'
    existing = shell_rc.read_text(encoding="utf-8")
    if source_line not in existing.splitlines():
        with shell_rc.open("a", encoding="utf-8") as f:
            f.write(f"\n{source_line}\n")


def _is_tcp_reachable(host: str, port: int, timeout_s: float = 1.0) -> bool:
    import socket

    try:
        with socket.create_connection((host, port), timeout=timeout_s):
            return True
    except OSError:
        return False


def run_setup_stack(args: argparse.Namespace) -> int:
    redis_url = args.redis_url
    redis_host, redis_port = _parse_redis_host_port(redis_url)

    if _is_tcp_reachable(redis_host, redis_port):
        print(f"Redis already reachable at {redis_url}")
    else:
        if args.skip_redis_start:
            raise RuntimeError(
                f"Redis is not reachable at {redis_url} and --skip-redis-start was set."
            )
        if redis_host not in {"127.0.0.1", "localhost"}:
            raise RuntimeError(
                f"Redis is not reachable at {redis_url} and host {redis_host!r} is not local."
            )
        redis_server = shutil.which("redis-server")
        if not redis_server:
            raise RuntimeError(
                "redis-server is not installed. Install Redis or point "
                "--redis-url at an existing shared Redis service."
            )
        state_dir = Path.home() / ".gpulane" / "redis" / str(redis_port)
        state_dir.mkdir(parents=True, exist_ok=True)
        pid_file = state_dir / "redis.pid"
        log_file = state_dir / "redis.log"
        print(f"Starting local Redis at {redis_url} ...")
        subprocess.run(
            [
                redis_server,
                "--bind",
                "127.0.0.1",
                "--port",
                str(redis_port),
                "--daemonize",
                "yes",
                "--dir",
                str(state_dir),
                "--pidfile",
                str(pid_file),
                "--logfile",
                str(log_file),
                "--save",
                "",
                "--appendonly",
                "no",
            ],
            check=True,
        )
        deadline = time.time() + 5
        while time.time() < deadline:
            if _is_tcp_reachable(redis_host, redis_port):
                break
            time.sleep(0.1)
        else:
            raise RuntimeError(
                f"Redis did not become ready within 5s. Check {log_file}"
            )
        print(f"Redis is ready at {redis_url}")

    env_file = Path(args.env_file).expanduser().resolve()
    shell_rc = None if args.no_shell_rc else Path(args.shell_rc).expanduser().resolve()
    _write_setup_env_file(
        env_file=env_file,
        ray_address=args.ray_address,
        redis_url=redis_url,
        shell_rc=shell_rc,
    )

    print()
    print(f"Wrote gpulane environment to: {env_file}")
    print("Configured values:")
    print(f"  GPULANE_RAY_ADDRESS={args.ray_address}")
    print(f"  GPULANE_REDIS_URL={redis_url}")
    print()
    print("gpulane stack is ready.")
    print("Shared on this workstation:")
    print(f"  Redis: {redis_url}")
    print("Per-user shell config:")
    print(f"  Env file: {env_file}")
    if shell_rc is not None:
        print(f"  Shell rc: {shell_rc}")
        print("Open a new shell or run:")
        print(f'  source "{env_file}"')
    else:
        print("Load manually with:")
        print(f'  source "{env_file}"')
    return 0
