#!/usr/bin/env bash

set -euo pipefail

RAY_ADDRESS="http://127.0.0.1:8265"
REDIS_URL="redis://127.0.0.1:6379"
ENV_FILE="$HOME/.gpulane/env.sh"
SHELL_RC="$HOME/.bashrc"
UPDATE_SHELL_RC=1
SKIP_REDIS_START=0
REDIS_WAIT_SECONDS=5

usage() {
  cat <<'EOF'
Usage:
  setup_gpulane_stack.sh [options]

This script:
1. Ensures a Redis backend is reachable
2. Starts a local redis-server if needed and possible
3. Writes gpulane environment exports

Options:
  --ray-address URL        Set GPULANE_RAY_ADDRESS
  --redis-url URL          Set GPULANE_REDIS_URL
  --env-file PATH          Write exports to this file
  --shell-rc PATH          Append a source line to this shell rc file
  --no-shell-rc            Do not modify ~/.bashrc or any shell rc file
  --skip-redis-start       Only verify Redis; do not start a local redis-server
  -h, --help               Show this help

Examples:
  ./scripts/setup_gpulane_stack.sh
  ./scripts/setup_gpulane_stack.sh --redis-url redis://127.0.0.1:6380
EOF
}

parse_redis_url() {
  local url="$1"
  if [[ "$url" =~ ^redis://([^:/]+)(:([0-9]+))?$ ]]; then
    REDIS_HOST="${BASH_REMATCH[1]}"
    REDIS_PORT="${BASH_REMATCH[3]:-6379}"
    return 0
  fi
  echo "Unsupported Redis URL format: $url" >&2
  echo "Expected format: redis://host:port" >&2
  exit 1
}

redis_is_reachable() {
  if command -v redis-cli >/dev/null 2>&1; then
    local pong
    pong="$(redis-cli -u "$REDIS_URL" ping 2>/dev/null || true)"
    [[ "$pong" == "PONG" ]]
    return
  fi
  (echo >"/dev/tcp/$REDIS_HOST/$REDIS_PORT") >/dev/null 2>&1
}

start_local_redis() {
  if [[ "$REDIS_HOST" != "127.0.0.1" && "$REDIS_HOST" != "localhost" ]]; then
    echo "Redis is not reachable at $REDIS_URL and host is not local, so it cannot be started automatically." >&2
    exit 1
  fi
  if ! command -v redis-server >/dev/null 2>&1; then
    echo "redis-server is not installed and Redis is not reachable at $REDIS_URL." >&2
    echo "Install Redis or point --redis-url at an existing shared Redis service." >&2
    exit 1
  fi

  local state_dir pid_file log_file
  state_dir="$HOME/.gpulane/redis/$REDIS_PORT"
  pid_file="$state_dir/redis.pid"
  log_file="$state_dir/redis.log"
  mkdir -p "$state_dir"

  echo "Starting local Redis at $REDIS_URL ..."
  redis-server \
    --bind 127.0.0.1 \
    --port "$REDIS_PORT" \
    --daemonize yes \
    --dir "$state_dir" \
    --pidfile "$pid_file" \
    --logfile "$log_file" \
    --save "" \
    --appendonly no

  local i
  for ((i = 0; i < REDIS_WAIT_SECONDS * 10; i++)); do
    if redis_is_reachable; then
      echo "Redis is ready at $REDIS_URL"
      return 0
    fi
    sleep 0.1
  done

  echo "Redis did not become ready within ${REDIS_WAIT_SECONDS}s. Check $log_file" >&2
  exit 1
}

write_env_file() {
  mkdir -p "$(dirname "$ENV_FILE")"

  cat >"$ENV_FILE" <<EOF
# Generated by scripts/setup_gpulane_stack.sh
export GPULANE_RAY_ADDRESS=$(printf '%q' "$RAY_ADDRESS")
export GPULANE_REDIS_URL=$(printf '%q' "$REDIS_URL")
EOF

  if [[ "$UPDATE_SHELL_RC" -eq 1 ]]; then
    mkdir -p "$(dirname "$SHELL_RC")"
    touch "$SHELL_RC"
    local source_line
    source_line="source \"$ENV_FILE\""
    if ! grep -Fqx "$source_line" "$SHELL_RC"; then
      printf '\n%s\n' "$source_line" >>"$SHELL_RC"
    fi
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ray-address)
      RAY_ADDRESS="${2:?missing value for --ray-address}"
      shift 2
      ;;
    --redis-url)
      REDIS_URL="${2:?missing value for --redis-url}"
      shift 2
      ;;
    --env-file)
      ENV_FILE="${2:?missing value for --env-file}"
      shift 2
      ;;
    --shell-rc)
      SHELL_RC="${2:?missing value for --shell-rc}"
      shift 2
      ;;
    --no-shell-rc)
      UPDATE_SHELL_RC=0
      shift
      ;;
    --skip-redis-start)
      SKIP_REDIS_START=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

parse_redis_url "$REDIS_URL"

if redis_is_reachable; then
  echo "Redis already reachable at $REDIS_URL"
elif [[ "$SKIP_REDIS_START" -eq 1 ]]; then
  echo "Redis is not reachable at $REDIS_URL and --skip-redis-start was set." >&2
  exit 1
else
  start_local_redis
fi

write_env_file

echo
echo "Wrote gpulane environment to: $ENV_FILE"
echo "Configured values:"
echo "  GPULANE_RAY_ADDRESS=$RAY_ADDRESS"
echo "  GPULANE_REDIS_URL=$REDIS_URL"
echo
echo "gpulane stack is ready."
echo "Shared on this workstation:"
echo "  Redis: $REDIS_URL"
echo "Per-user shell config:"
echo "  Env file: $ENV_FILE"
if [[ "$UPDATE_SHELL_RC" -eq 1 ]]; then
  echo "  Shell rc: $SHELL_RC"
  echo "Open a new shell or run:"
  echo "  source \"$ENV_FILE\""
else
  echo "Load manually with:"
  echo "  source \"$ENV_FILE\""
fi
